server_dev/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    url(r'^profile/(?P<pk>[0-9]+)/$', login_required(views.ProfileView.as_view()), name='profile'),
    path('profile_update/', login_required(views.ProfileUpdateView.as_view()), name='profile_update'),
]

server_dev/jariyo/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf.urls import url
from .views import base_views, shop_views
from django.shortcuts import render

app_name = 'jariyo'

urlpatterns = [
    # base_views.py
    path('main/', base_views.index, name='main'),
    path('map/', login_required(shop_views.MapView.as_view()), name='map'),
    path('restaurant/', login_required(shop_views.RestaurantView.as_view()), name='restaurant'),
    path('cafe/', login_required(shop_views.CafeView.as_view()), name='cafe'),
    url(r'^status/(?P<pk>[0-9]+)/$', login_required(shop_views.StatusView.as_view()), name='status'),
]

server_dev/server_dev/urls.py
from django.contrib import admin
from django.urls import path, include
from jariyo.views import base_views

urlpatterns = [
    path('jariyo/', include('jariyo.urls')),
    path('account/', include('account.urls')),
    path('manage/', include('smanager.urls')),
    path('admin/', admin.site.urls),
    path('', base_views.index, name='index'),
]

server_dev/smanager/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'smanager'

urlpatterns = [
    path('list/', login_required(views.ShopView.as_view()), name='list'),
    path('create/', login_required(views.ShopCreateView.as_view()), name='create'),
    path('update/<int:s_id>', login_required(views.ShopUpdateView.as_view()), name='update'),
]

server_dev/jariyo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import URLField
from account.models import Photo, user_path
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Shop(models.Model):
    SHOP_TYPES = [
        ('R', 'Restaurant'),
        ('C', 'Cafe'),
    ]
    manager = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    main_photo = models.ImageField(upload_to=user_path,blank=True, null=True)
    address = models.CharField(max_length=100,blank=True)
    phone = PhoneNumberField(null=True, blank=False)
    latitude = models.FloatField()
    longitude = models.FloatField()
    shop_type = models.CharField(blank=False, choices=SHOP_TYPES, max_length=1)
    site = models.URLField(blank=True)
    ispermited = models.BooleanField(default=False)

    sit_over4_max = models.IntegerField(default=0)
    sit_4_max = models.IntegerField(default=0)
    sit_2_max = models.IntegerField(default=0)

    sit_over4 = models.IntegerField(default=0)
    sit_4 = models.IntegerField(default=0)
    sit_2 = models.IntegerField(default=0)

class TimeStamedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

class Review(TimeStamedModel):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

server_dev/jariyo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.models import User

def index(request):
    cur_user = request.user
    
    if cur_user.is_authenticated:
        username = User.objects.get(username=request.user)
        return render(request, 'jariyo/index.html', {'username':username})
    else:
        return render(request, 'account/login.html')

server_dev/jariyo/views/shop_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.views.generic.detail import DetailView
from jariyo.models import Shop
from django.views import View
from django.core.paginator import Paginator
import json

class StatusView(DetailView):
    model = Shop
    template_name = 'jariyo/status.html'

class MapView(View):
    def get(self, request):
        shop_list = Shop.objects.all()
        shopdict = []
        for shop in shop_list:
            content = {
                "name": shop.name,
                "latitude": shop.latitude,
                "longitude": shop.longitude,
                "type": shop.shop_type,
            }
            shopdict.append(content)
        shopJson = json.dumps(shopdict)
        page = request.GET.get('page') # 페이지 번호 알아오기
        if page is None:
                page = 1
        else:
                page = int(page)
        paginator = Paginator(shop_list, 10)
        page_obj = paginator.get_page(page)
        context = {
                'shop_list': page_obj,
                'shopJson': shopJson,
                }
        return render(request, 'jariyo/map.html', context)

class RestaurantView(View):
    def get(self, request):
        shop_list = Shop.objects.filter(shop_type="R")

        # 페이징처리
        page = request.GET.get('page') # 페이지 번호 알아오기
        if page is None:
                page = 1
        else:
                page = int(page)
        paginator = Paginator(shop_list, 10)
        page_obj = paginator.get_page(page)
        context = {'shop_list': page_obj}

        return render(request, 'jariyo/list.html', context)

class CafeView(View):
    def get(self, request):
        shop_list = Shop.objects.filter(shop_type="C")

        # 페이징처리
        page = request.GET.get('page') # 페이지 번호 알아오기
        if page is None:
                page = 1
        else:
                page = int(page)
        paginator = Paginator(shop_list, 10)
        page_obj = paginator.get_page(page)
        context = {'shop_list': page_obj}

        return render(request, 'jariyo/list.html', context)

server_dev/templates/jariyo/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">

    <!-- base CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'jariyo/css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'jariyo/css/style.css' %}">
    <title>자리요</title>

</head>
<body>
    {% include "jariyo/navbar.html" %}
    <!-- Content -->
    {% block content %}
    {% endblock %}
    <!-- Content -->

    <!-- Script -->
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=f2e1c9d8fb54a31e342c11719d5482d0&libraries=services"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/npm.js' %}"></script>
    <script src="{% static 'jariyo/js/navbar.js' %}"></script>
    <!-- Script -->
</body>
</html>

server_dev/templates/jariyo/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div id="logo">
        <a herf="#"><img class="logo" src="{% static 'jariyo/img/main.png' %}"/></a>
    </div>
    <div class="row">
        <a href="{% url 'jariyo:map' %}"><img class="icon" src="{% static 'jariyo/img/map.png' %}" alt="지도">
    </div>
    <div class="row">
        <a href="{% url 'jariyo:restaurant' %}">
            <img class="icon" src="{% static 'jariyo/img/food.png' %}" alt="음식점">
        </a>
        <a href="{% url 'jariyo:cafe' %}">
            <img class="icon" src="{% static 'jariyo/img/cafe.png' %}" alt="카페">
        </a>
    </div>
</div>
{% endblock %}

server_dev/templates/jariyo/list.html
{% extends 'jariyo/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'jariyo/css/list.css' %}">
<div class="container my-3 main">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>가게이름</th>
            </tr>
        </thead>
        <tbody>
            {% if shop_list %}
            {% for shop in shop_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'jariyo:status' shop.id %}">{{ shop.name }}</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">등록된 가게가 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <div class="page-container">
        <ul>
            <!-- 이전페이지 -->
            {% if shop_list.has_previous %}
            <li class="item">
                <button class="page-link" href="?page={{ shop_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="item disabled">
                <button class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in shop_list.paginator.page_range %}
            {% if page_number >= shop_list.number|add:-5 and page_number <= shop_list.number|add:5 %}
            {% if page_number == shop_list.number %}
            <li class="item active" aria-current="page">
                <button class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="item">
                <button class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if shop_list.has_next %}
            <li class="page-item">
                <button class="page-link" href="?page={{ shop_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <button class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
    </div>
    <!-- 페이징처리 끝 -->
</div>
{% endblock %}

server_dev/templates/jariyo/map.html
{% extends 'jariyo/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'jariyo/css/map.css' %}">
<div id="map"></div>
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>가게이름</th>
            </tr>
        </thead>
        <tbody>
            {% if shop_list %}
            {% for shop in shop_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'jariyo:status' shop.id %}">{{ shop.name }}</a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">등록된 가게가 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if shop_list.has_previous %}
        <li class="page-item">
            <button class="page-link" onclick = "location.href='?page={{ shop_list.previous_page_number }}'">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <button class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in shop_list.paginator.page_range %}
        {% if page_number >= shop_list.number|add:-5 and page_number <= shop_list.number|add:5 %}
        {% if page_number == shop_list.number %}
        <li class="page-item active" aria-current="page">
            <button class="page-link" onclick = "location.href='?page={{ page_number }}'">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <button class="page-link" onclick = "location.href='?page={{ page_number }}'">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if shop_list.has_next %}
        <li class="page-item">
            <button class="page-link" onclick = "location.href='?page={{ shop_list.next_page_number }}'">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <button class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=	f2e1c9d8fb54a31e342c11719d5482d0"></script>
<script type="text/javascript" src="{% static 'jariyo/js/map.js' %}"></script>
{% endblock %}

server_dev/templates/jariyo/navbar.html
<!-- 네비게이션바 -->
{% load static %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-menu-hamburger" onclick="openNav()"></span></a>
      </div>
    </div><!-- /.container-fluid -->
  </nav>
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span class="glyphicon glyphicon-remove"></span></a>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1 col-xs-2" id="div_profile_img">
                {% if user.profile.profile_photo %}
                    <img class="img-circle" id="profile_img" src="{{user.profile.profile_photo.url}}">
                {% else %}
                    <img class="img-circle" id="profile_img" src="{% static 'account/images/default_profile.png' %}">
                {% endif %}
            </div>
            <div class="col-md-1 col-xs-4" id="profile_name">
                <a href="{% url 'account:profile' user.pk %}">
                    {% if user.profile.nickname %}
                        {{ user.profile.nickname }}
                    {% else %}
                        {{ user.username }}
                    {% endif %}
                </a>
            </div>
        </div>
    </div>
    <a href="{% url 'jariyo:main' %}"><span class="glyphicon glyphicon-home"></span> Home</a>
    <a href="{% url 'jariyo:map' %}"><span class="glyphicon glyphicon-globe"></span> 지도</a>
    <a href="{% url 'jariyo:restaurant' %}"><span class="glyphicon glyphicon-apple"></span> 음식점</a>
    <a href="{% url 'jariyo:cafe' %}"><span class="glyphicon glyphicon-leaf"></span> 카페</a>

    {% if user.profile.ismanager %}
    <a href="{% url 'smanager:list' %}"><span class="glyphicon glyphicon-cog"></span> 매장 관리</a>
    {% endif %}

    <a href="{% url 'account:logout' %}" id="logout">로그아웃</a>
</div>

server_dev/templates/jariyo/status.html
{% extends 'jariyo/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'jariyo/css/status.css' %}">
<div class="row">
    <div class="shop-img">
        {% if shop.main_photo %}
        <img class="img-circle" src="{{ shop.main_photo.url }}" width="300px" height="300px"> <br>
        {% else %}
        <img class="img-circle" src="{% static 'jariyo/img/default_main_photo.png' %}" width="300px" height="300px"> <br>
        {% endif %}
    </div>

    <div class="seat-list">
        <h2>{{ shop.name }}</h2>
        <ul>
            <li><span class="head">4인 이상 : </span><span class="tail">{{ shop.sit_over4_max }} / {{ shop.sit_over4 }}</span></li>
            <li><span class="head">4인석 : </span><span class="tail">{{ shop.sit_4_max }} / {{ shop.sit_4 }}</span></li>
            <li><span class="head">2인석 : </span><span class="tail">{{ shop.sit_2_max }} / {{ shop.sit_2 }}</span></li>
        </ul>
    </div>
    <button class="back-btn" onclick="back();">돌아가기</button>
</div>


<script>
    const back = () => {
        window.history.back();
    }
</script>
{% endblock %}