server_dev/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    url(r'^profile/(?P<pk>[0-9]+)/$', login_required(views.ProfileView.as_view()), name='profile'),
    path('profile_update/', login_required(views.ProfileUpdateView.as_view()), name='profile_update'),
]

server_dev/jariyo/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.conf.urls import url
from .views import base_views, shop_views
from django.shortcuts import render

app_name = 'jariyo'

urlpatterns = [
    # base_views.py
    path('main/', base_views.index, name='main'),
    path('map/', login_required(shop_views.MapView.as_view()), name='map'),
    path('restaurant/', login_required(shop_views.RestaurantView.as_view()), name='restaurant'),
    path('cafe/', login_required(shop_views.CafeView.as_view()), name='cafe'),
    url(r'^status/(?P<pk>[0-9]+)/$', login_required(shop_views.StatusView.as_view()), name='status'),
]

server_dev/server_dev/urls.py
from django.contrib import admin
from django.urls import path, include
from jariyo.views import base_views

urlpatterns = [
    path('jariyo/', include('jariyo.urls')),
    path('account/', include('account.urls')),
    path('manage/', include('smanager.urls')),
    path('admin/', admin.site.urls),
    path('', base_views.index, name='index'),
]

server_dev/smanager/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'smanager'

urlpatterns = [
    path('list/', login_required(views.ShopView.as_view()), name='list'),
    path('create/', login_required(views.ShopCreateView.as_view()), name='create'),
    path('update/<int:s_id>', login_required(views.ShopUpdateView.as_view()), name='update'),
]

server_dev/jariyo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import URLField
from account.models import Photo, user_path
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Shop(models.Model):
    SHOP_TYPES = [
        ('R', 'Restaurant'),
        ('C', 'Cafe'),
    ]
    manager = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    main_photo = models.ImageField(upload_to=user_path,blank=True, null=True)
    address = models.CharField(max_length=100,blank=True)
    phone = PhoneNumberField(null=True, blank=False)
    latitude = models.FloatField()
    longitude = models.FloatField()
    shop_type = models.CharField(blank=False, choices=SHOP_TYPES, max_length=1)
    site = models.URLField(blank=True)
    ispermited = models.BooleanField(default=False)

    sit_over4_max = models.IntegerField(default=0)
    sit_4_max = models.IntegerField(default=0)
    sit_2_max = models.IntegerField(default=0)

    sit_over4 = models.IntegerField(default=0)
    sit_4 = models.IntegerField(default=0)
    sit_2 = models.IntegerField(default=0)

class TimeStamedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

class Review(TimeStamedModel):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

server_dev/smanager/models.py
from django.db import models

# Create your models here.

server_dev/smanager/forms.py
from django import forms
from jariyo.models import Shop

# Create your models here.

class ShopCreateForm(forms.ModelForm):
    profile_photo = forms.ImageField(required=False)
    class Meta:
        model = Shop
        fields = [
            'name',
            'main_photo',
            'latitude',
            'longitude',
            'shop_type',
            'site',
            'sit_over4_max',
            'sit_4_max',
            'sit_2_max',
        ]
        labels = {
            'name': '가게이름',
            'main_photo': '사진',
            'latitude': '위도',
            'longitude': '경도',
            'shop_type': '카테고리',
            'site': '웹사이트 주소',
            'sit_over4_max': '4인이상 최대:',
            'sit_4_max': '4인석 최대:',
            'sit_2_max': '2인석 최대:',
        }  

class SeatUpdateForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = [
            'name',
            'sit_over4',
            'sit_4',
            'sit_2',
        ]

class ShopUpdateForm(forms.ModelForm):
    profile_photo = forms.ImageField(required=False)
    class Meta:
        model = Shop
        fields = [
            'name',
            'main_photo',
            'latitude',
            'longitude',
            'shop_type',
            'site',
            'sit_over4_max',
            'sit_4_max',
            'sit_2_max',
        ]
        labels = {
            'name': '가게이름',
            'main_photo': '사진',
            'latitude': '위도',
            'longitude': '경도',
            'shop_type': '카테고리',
            'site': '웹사이트 주소',
            'sit_over4_max': '4인이상 최대:',
            'sit_4_max': '4인석 최대:',
            'sit_2_max': '2인석 최대:',
        }  
        

server_dev/jariyo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.models import User

def index(request):
    cur_user = request.user
    
    if cur_user.is_authenticated:
        username = User.objects.get(username=request.user)
        return render(request, 'jariyo/index.html', {'username':username})
    else:
        return render(request, 'account/login.html')

server_dev/smanager/views.py
from django.http import request
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.views import View
from django.core.paginator import Paginator
from .forms import SeatUpdateForm, ShopCreateForm, ShopUpdateForm
from jariyo.models import Shop
from django.contrib import messages

class ShopView(View):
    def get(self, request):
        user = get_object_or_404(User, pk=request.user.pk) # 로그인중인 사용자 객체를 얻어옴

            # 조회
        if user.profile.ismanager:
            shop_list = user.shop_set.all() # 나의 가게만

            # 페이징처리
            page = request.GET.get('page') # 페이지 번호 알아오기
            if page is None:
                    page = 1
            else:
                    page = int(page)
            paginator = Paginator(shop_list, 1)  # 페이지당 1개씩 보여주기
            page_obj = paginator.get_page(page)
            context = {'shop_list': page_obj}

            return render(request, 'smanager/list.html', context)
        else:
            return redirect(request, 'jariyo:main')

    def post(self, request):
        u = User.objects.get(id=request.user.pk)
        s = get_object_or_404(u.shop_set.filter(name=request.POST.get('name')))

        form = SeatUpdateForm(request.POST, request.FILES, instance=s)

        if form.is_valid():
            seat = form.save(commit=False)
            seat.save()
            user = get_object_or_404(User, pk=request.user.pk)
            if user.profile.ismanager:
                shop_list = user.shop_set.all()
                page = int(request.GET.get('page'))
                paginator = Paginator(shop_list, 1)
                page_obj = paginator.get_page(page)
                context = {'shop_list': page_obj}

                return render(request, 'smanager/list.html', context)
        else:
            return redirect(request, 'smanager:list')

class ShopCreateView(View):
    def post(self, request):
        form = ShopCreateForm(request.POST, request.FILES)
        if form.is_valid():
            shop = form.save(commit=False)
            shop.manager = request.user
            shop.save()
        return redirect('smanager:list')

    def get(self, request):
        form = ShopCreateForm()
        content = {'form': form}
        return render(request, 'smanager/create.html', content)

class ShopUpdateView(View):
    def post(self, request, s_id):
        u = User.objects.get(id=request.user.pk)
        s = Shop.objects.get(id=s_id)
        if u == s.manager:
            form = ShopUpdateForm(request.POST, request.FILES, instance=s)
            if form.is_valid():
                shop = form.save(commit=False)
                shop.manager = u
                shop.save()
            return redirect('smanager:list')
        else:
            return redirect(request, 'jariyo:main')

    def get(self, request, s_id):
        form = ShopUpdateForm()
        shop = Shop.objects.get(id=s_id)
        u = User.objects.get(id=request.user.pk)
        if u == shop.manager:
            content = {
                'form': form,
                'shop': shop,
                }
            return render(request, 'smanager/update.html', content)
        else:
            return redirect(request, 'jariyo:main')

server_dev/templates/smanager/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">

    <!-- base CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'smanager/css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'smanager/css/style.css' %}">
    <title>자리요</title>

</head>
<body>
    {% include "smanager/navbar.html" %}
    <!-- Content -->
    {% block content %}
    {% endblock %}
    <!-- Content -->

    <!-- Script -->
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=f2e1c9d8fb54a31e342c11719d5482d0&libraries=services"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/npm.js' %}"></script>
    <script src="{% static 'smanager/js/navbar.js' %}"></script>
    <!-- Script -->
</body>
</html>

server_dev/templates/smanager/create.html
{% extends 'smanager/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'smanager/css/create.css' %}">
<div class="map_wrap">
    <div id="map" style="width:100%;height:100%;position:relative;overflow:hidden;"></div>

    <div id="menu_wrap" class="bg_white">
        <div class="option">
            <div>
                <form onsubmit="searchPlaces(); return false;">
                    키워드 : <input type="text" value="가게 이름" id="keyword" size="15">
                    <button type="submit">검색하기</button>
                </form>
            </div>
        </div>
        <hr>
        <ul id="placesList"></ul>
        <div id="pagination"></div>
    </div>
</div>
<div class="container">
    <p class="title">가게등록</p>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
            <div class="form-container">
                <ul>{{ form.as_ul }}</ul>
            </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

<script type="text/javascript"
    src="//dapi.kakao.com/v2/maps/sdk.js?appkey=f2e1c9d8fb54a31e342c11719d5482d0&libraries=services&libraries=services">
</script>
<script type="text/javascript"
    src="{% static 'smanager/js/create.js' %}">
</script>
{% endblock %}

server_dev/templates/smanager/list.html
{% extends 'smanager/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'smanager/css/list.css' %}">
{% if shop_list %}
{% for shop in shop_list %}
<div class="main-container">
    <h1>{{ shop.name }}<br></h1>

    <form method="post" class="post-form" action="{% url 'smanager:list' %}">
        {% csrf_token %}
        <input type="hidden" name="name" id="name" value="{{ shop.name }}">
        <div class="row">
            <label for="sit_over4">4인이상: {{ shop.sit_over4_max }} / </label>
            <input type="text" name="sit_over4" id="sit_over4" value="{{ shop.sit_over4|default_if_none:'0' }}">
        </div>
        <div class="row">
            <label for="sit_4">4인석: {{ shop.sit_4_max }} / </label>
            <input type="text" name="sit_4" id="sit_4" value="{{ shop.sit_4|default_if_none:'0' }}">
        </div>
        <div class="row">
            <label for="sit_2">2인석: {{ shop.sit_2_max }} / </label>
            <input type="text" name="sit_2" id="sit_2" value="{{ shop.sit_2|default_if_none:'0' }}">
        </div>
        <div class="row">
            <button type="submit">자리 정보 업데이트</button>
        </div>
    </form>

    <a href="{% url 'smanager:update' shop.id %}">매장 정보 수정</a>
    {% endfor %}
    {% else %}매장이 없습니다.{% endif %}

</div>



{% endblock %}

server_dev/templates/smanager/map.html
{% extends 'smanager/base.html' %}
{% block content %}
{% load static %}
<div class="map_wrap">
    <div id="map" style="width:100%;height:100%;position:relative;overflow:hidden;"></div>

    <div id="menu_wrap" class="bg_white">
        <div class="option">
            <div>
                <form onsubmit="searchPlaces(); return false;">
                    키워드 : <input type="text" value="이태원 맛집" id="keyword" size="15"> 
                    <button type="submit">검색하기</button> 
                </form>
            </div>
        </div>
        <hr>
        <ul id="placesList"></ul>
        <div id="pagination"></div>
    </div>
</div>

<script type="text/javascript" src="{% static 'smanager/js/cacaomap.js' %}"></script>
{% endblock %}

server_dev/templates/smanager/navbar.html
<!-- 네비게이션바 -->
{% load static %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-menu-hamburger" onclick="openNav()"></span></a>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        {% for page_number in shop_list.paginator.page_range %}
            {% if page_number == shop_list.number %}
            <li class="active"><a href="?page={{ page_number }}">{{ page_number }}<span class="sr-only">(current)</span></a></li>
            {% else %}
            <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %}
        {% endfor %}
        <li><a href="{% url 'smanager:create' %}">+</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><span class="glyphicon glyphicon-remove"></span></a>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1 col-xs-2" id="div_profile_img">
                {% if user.profile.profile_photo %}
                    <img class="img-circle" id="profile_img" src="{{user.profile.profile_photo.url}}">
                {% else %}
                    <img class="img-circle" id="profile_img" src="{% static 'account/images/default_profile.png' %}">
                {% endif %}
            </div>
            <div class="col-md-1 col-xs-4" id="profile_name">
                <a href="{% url 'account:profile' user.pk %}">
                    {% if user.profile.nickname %}
                        {{ user.profile.nickname }}
                    {% else %}
                        {{ user.username }}
                    {% endif %}
                </a>
            </div>
        </div>
    </div>
    <a href="{% url 'jariyo:main' %}"><span class="glyphicon glyphicon-home"></span> Home</a>
    <a href="{% url 'jariyo:map' %}"><span class="glyphicon glyphicon-globe"></span> 지도</a>
    <a href="{% url 'jariyo:restaurant' %}"><span class="glyphicon glyphicon-apple"></span> 음식점</a>
    <a href="{% url 'jariyo:cafe' %}"><span class="glyphicon glyphicon-leaf"></span> 카페</a>

    {% if user.profile.ismanager %}
    <a href="{% url 'smanager:list' %}"><span class="glyphicon glyphicon-cog"></span> 매장 관리</a>
    {% endif %}

    <a href="{% url 'account:logout' %}" id="logout">로그아웃</a>
</div>

server_dev/templates/smanager/update.html
{% extends 'smanager/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'smanager/css/update.css' %}">
<div class="map_wrap">
    <div id="map" style="width:100%;height:100%;position:relative;overflow:hidden;"></div>

    <div id="menu_wrap" class="bg_white">
        <div class="option">
            <div>
                <form onsubmit="searchPlaces(); return false;">
                    키워드 : <input type="text" value="{{ shop.name }}" id="keyword" size="15">
                    <button type="submit">검색하기</button>
                </form>
            </div>
        </div>
        <hr>
        <ul id="placesList"></ul>
        <div id="pagination"></div>
    </div>
</div>

<div class="container">
    <h5 class="my-3 border-bottom pb-2">가게정보 수정</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <div class="row">
            <label for="name">가게이름: </label>
            <input type="text" name="name" id="name" value="{{ shop.name }}">
        </div>
        <div class="row">
            {{ form.main_photo }}
        </div>
        <input type="hidden" name="latitude" id="latitude" value="{{ shop.latitude }}">
        <input type="hidden" name="longitude" id="longitude" value="{{ shop.longitude }}">
        <div class="row">
            <label for="shop_type">카테고리: </label>
            <select name="shop_type" required="" id="id_shop_type">
                <option value="" selected="">---------</option>
                <option value="R">음식점</option>
                <option value="C">카페</option>
            </select>
        </div>
        <div class="row">
            <label for="site">웹사이트 주소: </label>
            <input type="text" name="site" id="site" value="{{ shop.site }}">
        </div>
        <div class="row">
            <label for="sit_over4_max">4인이상 최대: </label>
            <input type="text" name="sit_over4_max" id="sit_over4_max" value="{{ shop.sit_over4_max }}">
        </div>
        <div class="row">
            <label for="sit_4_max">4인석 최대: </label>
            <input type="text" name="sit_4_max" id="sit_4_max" value="{{ shop.sit_4_max }}">
        </div>
        <div class="row">
            <label for="sit_2_max">2인석 최대: </label>
            <input type="text" name="sit_2_max" id="sit_2_max" value="{{ shop.sit_2_max }}">
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
<script type="text/javascript"
    src="//dapi.kakao.com/v2/maps/sdk.js?appkey=f2e1c9d8fb54a31e342c11719d5482d0&libraries=services&libraries=services">
</script>
<script type="text/javascript"
    src="{% static 'smanager/js/update.js' %}">
</script>
{% endblock %}